namespace AltMediatR.Core.Abstractions
{
    /// <summary>
    /// Implemented by code generated by AltMediatR.SourceGenerator to provide compile-time
    /// request dispatch, eliminating the need for runtime <c>MakeGenericMethod</c> reflection
    /// in the Mediator.  Register the generated implementation via <c>AddGeneratedHandlers()</c>.
    /// </summary>
    public interface ICompiledHandlerDispatcher
    {
        /// <summary>
        /// Attempts to dispatch a request/response request using compile-time-generated routing.
        /// Returns <c>true</c> and sets <paramref name="task"/> when the request type is known.
        /// Returns <c>false</c> when the request type was not present at compile time (falls back to reflection).
        /// </summary>
        bool TryDispatch<TResponse>(
            IPipelineDispatcher dispatcher,
            IRequest<TResponse> request,
            CancellationToken cancellationToken,
            out Task<TResponse>? task);

        /// <summary>
        /// Attempts to dispatch a void request using compile-time-generated routing.
        /// Returns <c>true</c> and sets <paramref name="task"/> when the request type is known.
        /// Returns <c>false</c> when the request type was not present at compile time (falls back to reflection).
        /// </summary>
        bool TryDispatchVoid(
            IPipelineDispatcher dispatcher,
            IRequest request,
            CancellationToken cancellationToken,
            out Task? task);
    }
}
