using System.ComponentModel;

namespace AltMediatR.Core.Abstractions
{
    /// <summary>
    /// Exposes the typed pipeline execution paths of the Mediator so that
    /// compiled dispatcher code generated by AltMediatR.SourceGenerator can route
    /// requests without runtime reflection (<c>MakeGenericMethod</c>/<c>Invoke</c>).
    /// Not intended for direct use by application code.
    /// </summary>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public interface IPipelineDispatcher
    {
        Task<TResponse> ExecutePipelineAsync<TRequest, TResponse>(TRequest request, CancellationToken cancellationToken)
            where TRequest : IRequest<TResponse>;

        Task ExecuteVoidPipelineAsync<TRequest>(TRequest request, CancellationToken cancellationToken)
            where TRequest : IRequest;
    }
}
